import React, { useState, useCallback } from 'react';
import { useStore } from '../context/StoreContext';
import { formatDate, formatDateTime } from '../lib/utils';
import { motion, AnimatePresence } from 'motion/react';
import { useDropzone } from 'react-dropzone';
import { 
  FileText, FileSpreadsheet, FileJson, Download, UploadCloud, 
  AlertCircle, CheckCircle2, FileArchive, ArrowRight, ShieldCheck,
  RefreshCcw, Info
} from 'lucide-react';
import Papa from 'papaparse';
import * as XLSX from 'xlsx';
import { saveAs } from 'file-saver';
import JSZip from 'jszip';
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { Transaction, AppState, ReceivedMoney, SentMoney, PendingMoney } from '../types';

declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: any) => jsPDF;
  }
}

export default function ImportExport() {
  const store = useStore();
  const [activeTab, setActiveTab] = useState<'export' | 'import'>('export');
  const [isProcessing, setIsProcessing] = useState(false);
  const [progress, setProgress] = useState(0);
  const [statusMsg, setStatusMsg] = useState('');
  
  // Import States
  const [parsedTransactions, setParsedTransactions] = useState<Transaction[]>([]);
  const [importPreview, setImportPreview] = useState(false);

  // Helper function to update progress
  const updateProgress = (val: number, msg: string) => {
    setProgress(val);
    setStatusMsg(msg);
  };

  // -------------------------------------------------------------
  // EXPORT LOGIC
  // -------------------------------------------------------------

  const generatePDF = async () => {
    setIsProcessing(true);
    updateProgress(20, 'Initializing PDF generator...');
    
    setTimeout(() => {
      try {
        const doc = new jsPDF();
        updateProgress(50, 'Adding report content...');
        
        doc.setFontSize(22);
        doc.text('SmartLedger Financial Report', 14, 22);
        
        doc.setFontSize(11);
        doc.text(`Generated: ${formatDateTime(new Date().toISOString(), store.generalSettings?.timezone)}`, 14, 30);
        
        doc.setFontSize(14);
        doc.text('Summary', 14, 45);
        
        doc.setFontSize(11);
        doc.text(`Current Balance: ₹${store.currentBalance.toLocaleString()}`, 14, 55);
        doc.text(`Total Income: ₹${store.totalReceived.toLocaleString()}`, 14, 62);
        doc.text(`Total Expenses: ₹${store.totalSent.toLocaleString()}`, 14, 69);
        doc.text(`Total Savings: ₹${(store.totalReceived - store.totalSent).toLocaleString()}`, 14, 76);
        doc.text(`Pending Amount: ₹${store.totalPending.toLocaleString()}`, 14, 83);
        
        updateProgress(70, 'Adding transaction table...');
        const tableData = store.transactions.map(t => [
          formatDate(t.type === 'pending' ? (t as PendingMoney).dueDate : (t as any).date, store.generalSettings?.timezone),
          t.type.toUpperCase(),
          t.personName,
          t.type === 'pending' ? (t as PendingMoney).reason : (t as any).purpose,
          `Rs ${t.amount.toLocaleString()}`,
          t.type === 'pending' ? (t as PendingMoney).status : 'COMPLETED'
        ]);
        
        doc.autoTable({
          startY: 95,
          head: [['Date', 'Type', 'Person/Entity', 'Description', 'Amount', 'Status']],
          body: tableData,
          theme: 'striped',
          styles: { fontSize: 9 },
          headStyles: { fillColor: [79, 70, 229] }
        });
        
        doc.setFontSize(10);
        doc.text('Generated by SmartLedger', 14, doc.internal.pageSize.height - 10);
        
        updateProgress(90, 'Saving PDF...');
        doc.save('SmartLedger_Financial_Report.pdf');
        
        updateProgress(100, 'Done!');
        setTimeout(() => setIsProcessing(false), 1000);
      } catch (err) {
        console.error(err);
        updateProgress(0, 'Export failed');
        setIsProcessing(false);
      }
    }, 500);
  };

  const generateExcel = async () => {
    setIsProcessing(true);
    updateProgress(30, 'Formatting Excel sheets...');
    
    try {
      const { generateAdvancedExcel } = await import('../lib/excelExport');
      const summary = {
        currentBalance: store.currentBalance,
        totalReceived: store.totalReceived,
        totalSent: store.totalSent,
        totalPending: store.totalPending
      };
      await generateAdvancedExcel(store.transactions, summary);
      
      updateProgress(100, 'Done!');
      setTimeout(() => setIsProcessing(false), 1000);
    } catch (err) {
      console.error(err);
      updateProgress(0, 'Export failed');
      setIsProcessing(false);
    }
  };

  const generateCSV = () => {
    setIsProcessing(true);
    updateProgress(50, 'Generating CSV...');
    
    setTimeout(() => {
      const data = store.transactions.map(t => ({
        Date: t.type === 'pending' ? (t as PendingMoney).dueDate : (t as any).date,
        Type: t.type,
        Category: 'General',
        Description: t.type === 'pending' ? (t as PendingMoney).reason : (t as any).purpose,
        Amount: t.amount,
        Status: t.type === 'pending' ? (t as PendingMoney).status : 'Completed',
        Person: t.personName,
        'Payment Method': 'Bank Transfer'
      }));
      
      const csv = Papa.unparse(data);
      const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
      saveAs(blob, 'SmartLedger_Transactions.csv');
      
      updateProgress(100, 'Done!');
      setTimeout(() => setIsProcessing(false), 1000);
    }, 500);
  };

  const createBackup = () => {
    setIsProcessing(true);
    updateProgress(50, 'Generating secure backup JSON...');
    
    setTimeout(() => {
      const backupData = JSON.stringify({
        isSetupComplete: store.isSetupComplete,
        startingBalance: store.startingBalance,
        transactions: store.transactions,
        securitySettings: store.securitySettings
      }, null, 2);
      
      const blob = new Blob([backupData], { type: 'application/json' });
      saveAs(blob, `SmartLedger_Backup_${new Date().toISOString().split('T')[0]}.json`);
      
      updateProgress(100, 'Backup Complete!');
      setTimeout(() => setIsProcessing(false), 1000);
    }, 500);
  };

  const generateZip = async () => {
    setIsProcessing(true);
    updateProgress(20, 'Preparing ZIP archive...');
    
    try {
      const zip = new JSZip();
      
      // JSON Backup
      const backupData = JSON.stringify({
        isSetupComplete: store.isSetupComplete,
        startingBalance: store.startingBalance,
        transactions: store.transactions,
        securitySettings: store.securitySettings
      }, null, 2);
      zip.file('Backup.json', backupData);
      
      // CSV
      updateProgress(40, 'Adding CSV records...');
      const csvData = store.transactions.map(t => ({
        Date: t.type === 'pending' ? (t as PendingMoney).dueDate : (t as any).date,
        Type: t.type,
        Category: 'General',
        Description: t.type === 'pending' ? (t as PendingMoney).reason : (t as any).purpose,
        Amount: t.amount,
        Status: t.type === 'pending' ? (t as PendingMoney).status : 'Completed',
        Person: t.personName,
        'Payment Method': 'Bank Transfer'
      }));
      zip.file('Transactions.csv', Papa.unparse(csvData));
      
      updateProgress(80, 'Compressing archive...');
      const content = await zip.generateAsync({ type: 'blob' });
      saveAs(content, 'SmartLedger_Complete_Export.zip');
      
      updateProgress(100, 'Done!');
      setTimeout(() => setIsProcessing(false), 1000);
    } catch (err) {
      console.error(err);
      updateProgress(0, 'Failed to create ZIP');
      setIsProcessing(false);
    }
  };


  // -------------------------------------------------------------
  // IMPORT LOGIC
  // -------------------------------------------------------------
  
  const onDrop = useCallback((acceptedFiles: File[]) => {
    const file = acceptedFiles[0];
    if (!file) return;

    setIsProcessing(true);
    updateProgress(20, 'Reading file...');

    const reader = new FileReader();

    reader.onload = (e) => {
      updateProgress(50, 'Parsing data...');
      try {
        const content = e.target?.result;
        
        if (file.name.endsWith('.json')) {
          const parsed = JSON.parse(content as string) as AppState;
          if (parsed && parsed.transactions) {
            setParsedTransactions(parsed.transactions);
            setImportPreview(true);
          } else {
             throw new Error('Invalid JSON structure');
          }
        } else if (file.name.endsWith('.csv')) {
           Papa.parse(content as string, {
             header: true,
             skipEmptyLines: true,
             complete: (results) => {
               // Map CSV to our structure
               const txs: Transaction[] = results.data.map((row: any) => {
                 const type = (row.Type || row.type || 'received').toLowerCase();
                 const amount = parseFloat(row.Amount || row.amount || '0');
                 const date = row.Date || row.date || new Date().toISOString().split('T')[0];
                 const person = row.Person || row.person || 'Unknown';
                 const desc = row.Description || row.description || '';
                 
                 const base = { id: crypto.randomUUID(), amount, personName: person };
                 
                 if (type === 'sent') return { ...base, type: 'sent', date, purpose: desc } as SentMoney;
                 if (type === 'pending') return { ...base, type: 'pending', dueDate: date, reason: desc, status: 'pending', reminderStatus: 'active', nextReminderDate: date } as PendingMoney;
                 return { ...base, type: 'received', date, purpose: desc } as ReceivedMoney;
               });
               setParsedTransactions(txs);
               setImportPreview(true);
             }
           });
        } else if (file.name.endsWith('.xlsx') || file.name.endsWith('.xls')) {
           const workbook = XLSX.read(content, { type: 'buffer' });
           const sheetName = workbook.SheetNames[0];
           const sheet = workbook.Sheets[sheetName];
           const data = XLSX.utils.sheet_to_json(sheet);
           
           const txs: Transaction[] = data.map((row: any) => {
                 const type = (row.Type || row.type || 'received').toLowerCase();
                 const amount = parseFloat(row.Amount || row.amount || '0');
                 // Excel dates might need conversion if they are numbers, but sheet_to_json handles format if raw: false
                 const date = row.Date || row.date || new Date().toISOString().split('T')[0];
                 const person = row.Person || row.person || 'Unknown';
                 const desc = row.Description || row.description || '';
                 
                 const base = { id: crypto.randomUUID(), amount, personName: person };
                 
                 if (type === 'sent') return { ...base, type: 'sent', date, purpose: desc } as SentMoney;
                 if (type === 'pending') return { ...base, type: 'pending', dueDate: date, reason: desc, status: 'pending', reminderStatus: 'active', nextReminderDate: date } as PendingMoney;
                 return { ...base, type: 'received', date, purpose: desc } as ReceivedMoney;
           });
           setParsedTransactions(txs);
           setImportPreview(true);
        }
        updateProgress(100, 'Ready for import');
      } catch (err) {
        console.error(err);
        updateProgress(0, 'Invalid file format');
      } finally {
        setTimeout(() => setIsProcessing(false), 500);
      }
    };

    if (file.name.endsWith('.json') || file.name.endsWith('.csv')) {
      reader.readAsText(file);
    } else if (file.name.endsWith('.xlsx') || file.name.endsWith('.xls')) {
      reader.readAsArrayBuffer(file);
    } else {
       setIsProcessing(false);
       alert("Please upload JSON, CSV, or Excel");
    }
  }, []);

  const { getRootProps, getInputProps, isDragActive } = useDropzone({ 
    onDrop,
    accept: {
      'application/json': ['.json'],
      'text/csv': ['.csv'],
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': ['.xlsx'],
      'application/vnd.ms-excel': ['.xls']
    },
    maxFiles: 1
  });

  const confirmImport = () => {
    if (!parsedTransactions.length) return;
    
    setIsProcessing(true);
    updateProgress(30, 'Merging transactions...');
    
    setTimeout(() => {
      // Merge with deduplication based on ID if available
      const existingIds = new Set(store.transactions.map(t => t.id));
      const newTxs = parsedTransactions.filter(t => !existingIds.has(t.id));
      
      const mergedApp = {
        ...store,
        transactions: [...newTxs, ...store.transactions]
      };
      
      store.importData(mergedApp);
      
      updateProgress(100, 'Import Successful!');
      setTimeout(() => {
        setIsProcessing(false);
        setImportPreview(false);
        setParsedTransactions([]);
      }, 1500);
    }, 800);
  };


  return (
    <div className="w-full flex flex-col gap-6">
      <header>
        <h1 className="text-3xl font-light text-white tracking-tight">Import & Export</h1>
        <p className="text-slate-400 mt-1">Manage your financial data securely</p>
      </header>

      {/* Custom Tabs */}
      <div className="flex gap-2 bg-[#0a0b10]/80 p-1 rounded-2xl w-fit border border-white/5 backdrop-blur-xl">
        <button
          onClick={() => setActiveTab('export')}
          className={`px-6 py-2 rounded-xl text-sm font-medium transition-all ${
            activeTab === 'export' ? 'bg-indigo-500 text-white shadow-lg shadow-indigo-500/20' : 'text-slate-400 hover:text-white'
          }`}
        >
          Export & Backup
        </button>
        <button
          onClick={() => setActiveTab('import')}
          className={`px-6 py-2 rounded-xl text-sm font-medium transition-all ${
            activeTab === 'import' ? 'bg-indigo-500 text-white shadow-lg shadow-indigo-500/20' : 'text-slate-400 hover:text-white'
          }`}
        >
          Import Data
        </button>
      </div>

      <AnimatePresence mode="wait">
        {activeTab === 'export' ? (
          <motion.div
            key="export"
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -10 }}
            className="grid grid-cols-1 md:grid-cols-2 gap-6"
          >
            {/* Download Everything */}
            <div className="col-span-1 md:col-span-2 bg-gradient-to-r from-indigo-500/10 to-blue-500/10 border border-indigo-500/20 rounded-3xl p-8 relative overflow-hidden flex flex-col md:flex-row items-center justify-between gap-6 group">
              <div className="absolute top-0 right-0 w-64 h-64 bg-indigo-500/10 rounded-full blur-[80px] group-hover:bg-indigo-500/20 transition-all duration-500"></div>
              
              <div className="relative z-10 flex-1">
                <div className="flex items-center gap-3 mb-2">
                  <FileArchive className="text-indigo-400" size={24} />
                  <h2 className="text-2xl font-light text-white">One-Click Download</h2>
                </div>
                <p className="text-slate-400 font-light max-w-xl">
                  Get a comprehensive ZIP archive containing your financial reports in PDF, all transactions in Excel & CSV formats, and a full system backup JSON.
                </p>
              </div>

              <button 
                onClick={generateZip}
                disabled={isProcessing}
                className="relative z-10 flex items-center justify-center gap-2 bg-indigo-500 hover:bg-indigo-600 text-white px-8 py-4 rounded-xl font-medium transition-all shadow-lg shadow-indigo-500/25 w-full md:w-auto disabled:opacity-50"
              >
                <Download size={20} />
                Download Everything
              </button>
            </div>

            {/* Individual Exports */}
            <div className="bg-[#0a0b10]/80 backdrop-blur-xl border border-white/5 rounded-3xl p-6 hover:border-white/10 transition-all">
              <div className="flex items-center gap-3 mb-6">
                <div className="w-10 h-10 bg-red-500/10 rounded-xl flex items-center justify-center text-red-400">
                  <FileText size={20} />
                </div>
                <div>
                  <h3 className="text-lg font-medium text-white">Export as PDF</h3>
                  <p className="text-xs text-slate-400">Professional financial report</p>
                </div>
              </div>
              <button onClick={generatePDF} disabled={isProcessing} className="w-full flex items-center justify-center gap-2 bg-white/5 hover:bg-white/10 text-white py-3 rounded-xl transition-colors border border-white/5">
                Generate PDF <ArrowRight size={16} className="text-slate-400" />
              </button>
            </div>

            <div className="bg-[#0a0b10]/80 backdrop-blur-xl border border-white/5 rounded-3xl p-6 hover:border-white/10 transition-all">
              <div className="flex items-center gap-3 mb-6">
                <div className="w-10 h-10 bg-emerald-500/10 rounded-xl flex items-center justify-center text-emerald-400">
                  <FileSpreadsheet size={20} />
                </div>
                <div>
                  <h3 className="text-lg font-medium text-white">Export as Excel</h3>
                  <p className="text-xs text-slate-400">Detailed sheets (.xlsx)</p>
                </div>
              </div>
              <button onClick={generateExcel} disabled={isProcessing} className="w-full flex items-center justify-center gap-2 bg-white/5 hover:bg-white/10 text-white py-3 rounded-xl transition-colors border border-white/5">
                Generate Excel <ArrowRight size={16} className="text-slate-400" />
              </button>
            </div>

            <div className="bg-[#0a0b10]/80 backdrop-blur-xl border border-white/5 rounded-3xl p-6 hover:border-white/10 transition-all">
              <div className="flex items-center gap-3 mb-6">
                <div className="w-10 h-10 bg-blue-500/10 rounded-xl flex items-center justify-center text-blue-400">
                  <FileText size={20} />
                </div>
                <div>
                  <h3 className="text-lg font-medium text-white">Export as CSV</h3>
                  <p className="text-xs text-slate-400">Raw transaction data</p>
                </div>
              </div>
              <button onClick={generateCSV} disabled={isProcessing} className="w-full flex items-center justify-center gap-2 bg-white/5 hover:bg-white/10 text-white py-3 rounded-xl transition-colors border border-white/5">
                Generate CSV <ArrowRight size={16} className="text-slate-400" />
              </button>
            </div>

            <div className="bg-[#0a0b10]/80 backdrop-blur-xl border border-white/5 rounded-3xl p-6 hover:border-white/10 transition-all relative overflow-hidden">
              <div className="absolute top-0 right-0 w-32 h-32 bg-amber-500/5 rounded-full blur-[50px]"></div>
              <div className="flex items-center gap-3 mb-6 relative z-10">
                <div className="w-10 h-10 bg-amber-500/10 rounded-xl flex items-center justify-center text-amber-400">
                  <FileJson size={20} />
                </div>
                <div>
                  <h3 className="text-lg font-medium text-white">Create System Backup</h3>
                  <p className="text-xs text-slate-400">Full JSON snapshot</p>
                </div>
              </div>
              <button onClick={createBackup} disabled={isProcessing} className="w-full relative z-10 flex items-center justify-center gap-2 bg-amber-500/10 hover:bg-amber-500/20 text-amber-400 py-3 rounded-xl transition-colors border border-amber-500/20">
                Create Backup <ArrowRight size={16} />
              </button>
            </div>

          </motion.div>
        ) : (
          <motion.div
            key="import"
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -10 }}
            className="space-y-6"
          >
            {importPreview ? (
               <div className="bg-[#0a0b10]/80 backdrop-blur-xl border border-white/5 rounded-3xl p-6">
                 <div className="flex items-center justify-between mb-6">
                    <div>
                      <h3 className="text-xl font-medium text-white">Preview Import</h3>
                      <p className="text-sm text-slate-400">Found {parsedTransactions.length} transactions</p>
                    </div>
                    <div className="flex gap-2">
                       <button onClick={() => { setImportPreview(false); setParsedTransactions([]); }} className="px-4 py-2 rounded-xl bg-white/5 text-white hover:bg-white/10 transition-colors">
                          Cancel
                       </button>
                       <button onClick={confirmImport} disabled={isProcessing} className="px-4 py-2 rounded-xl bg-indigo-500 text-white hover:bg-indigo-600 shadow-lg shadow-indigo-500/20 transition-all flex items-center gap-2">
                          <CheckCircle2 size={18} /> Confirm Import
                       </button>
                    </div>
                 </div>

                 <div className="bg-white/5 rounded-2xl overflow-hidden border border-white/5">
                    <div className="max-h-[400px] overflow-y-auto custom-scrollbar p-1">
                       {parsedTransactions.slice(0, 50).map((t, i) => (
                          <div key={i} className="flex items-center justify-between p-3 border-b border-white/5 last:border-0 hover:bg-white/5 transition-colors">
                             <div className="flex items-center gap-3">
                                <div className={`w-8 h-8 rounded-full flex items-center justify-center text-xs ${
                                   t.type === 'received' ? 'bg-emerald-500/20 text-emerald-400' :
                                   t.type === 'sent' ? 'bg-red-500/20 text-red-400' : 'bg-amber-500/20 text-amber-400'
                                }`}>
                                   {t.type === 'received' ? 'IN' : t.type === 'sent' ? 'OUT' : 'PEN'}
                                </div>
                                <div>
                                   <p className="text-white text-sm">{t.personName}</p>
                                   <p className="text-xs text-slate-400 font-light">{formatDate(t.type === 'pending' ? (t as PendingMoney).dueDate : (t as any).date, store.generalSettings?.timezone)}</p>
                                </div>
                             </div>
                             <p className={`font-medium text-sm ${
                                t.type === 'received' ? 'text-emerald-400' :
                                t.type === 'sent' ? 'text-red-400' : 'text-amber-400'
                             }`}>
                                {t.type === 'received' ? '+' : t.type === 'sent' ? '-' : ''}₹{t.amount.toLocaleString()}
                             </p>
                          </div>
                       ))}
                       {parsedTransactions.length > 50 && (
                          <p className="text-center text-slate-400 py-3 text-sm font-light border-t border-white/5">
                             + {parsedTransactions.length - 50} more records
                          </p>
                       )}
                    </div>
                 </div>
               </div>
            ) : (
              <div 
                {...getRootProps()} 
                className={`border-2 border-dashed rounded-3xl p-12 text-center transition-all cursor-pointer ${
                  isDragActive ? 'border-indigo-500 bg-indigo-500/5' : 'border-white/10 hover:border-white/20 hover:bg-white/5'
                }`}
              >
                <input {...getInputProps()} />
                <div className="w-20 h-20 bg-gradient-to-br from-indigo-500/20 to-blue-500/20 rounded-full mx-auto flex items-center justify-center mb-6 shadow-lg shadow-indigo-500/10">
                  <UploadCloud size={32} className="text-indigo-400" />
                </div>
                <h3 className="text-xl font-medium text-white mb-2">
                  {isDragActive ? 'Drop file to import' : 'Drag & drop file here'}
                </h3>
                <p className="text-slate-400 font-light mb-6">Supports .json, .csv bank statements</p>
                <button className="bg-white/10 hover:bg-white/15 text-white px-6 py-2.5 rounded-xl font-medium transition-colors border border-white/5">
                  Browse Files
                </button>
              </div>
            )}

            <div className="bg-blue-500/10 border border-blue-500/20 rounded-2xl p-5 flex items-start gap-4">
               <Info className="text-blue-400 shrink-0 mt-0.5" size={20} />
               <div>
                  <h4 className="text-blue-400 font-medium mb-1">Import Security</h4>
                  <p className="text-sm text-blue-200/70 font-light leading-relaxed">
                    All imported files are processed strictly on your local device. SmartLedger automatically detects and prevents duplicate transactions based on existing records to maintain data integrity.
                  </p>
               </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Global Processing Overlay */}
      <AnimatePresence>
        {isProcessing && (
          <motion.div 
            initial={{ opacity: 0 }} 
            animate={{ opacity: 1 }} 
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 bg-[#05060a]/80 backdrop-blur-md flex items-center justify-center p-4"
          >
             <div className="bg-[#0a0b10] border border-white/10 rounded-3xl p-8 max-w-sm w-full text-center shadow-2xl flex flex-col items-center">
                <RefreshCcw size={40} className="text-indigo-500 animate-spin mb-6" />
                <h3 className="text-xl font-light text-white mb-2">{statusMsg || 'Processing...'}</h3>
                <div className="w-full h-1.5 bg-white/10 rounded-full overflow-hidden mt-4">
                   <motion.div 
                     className="h-full bg-gradient-to-r from-indigo-500 to-blue-400"
                     initial={{ width: 0 }}
                     animate={{ width: `${progress}%` }}
                     transition={{ ease: "linear", duration: 0.2 }}
                   />
                </div>
             </div>
          </motion.div>
        )}
      </AnimatePresence>

    </div>
  );
}
