import React, { useState, useCallback, useMemo } from 'react';
import { useStore } from '../context/StoreContext';
import { formatDate, formatDateTime } from '../lib/utils';
import { motion, AnimatePresence } from 'motion/react';
import { useDropzone } from 'react-dropzone';
import { 
  FileText, FileSpreadsheet, FileJson, Download, UploadCloud, 
  AlertCircle, CheckCircle2, FileArchive, ArrowRight, ShieldCheck,
  RefreshCcw, Info, X, Filter, AlertTriangle, FileX, Check, CornerDownRight
} from 'lucide-react';
import Papa from 'papaparse';
import { saveAs } from 'file-saver';
import JSZip from 'jszip';
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { Transaction, AppState, ReceivedMoney, SentMoney, PendingMoney } from '../types';
import { 
  parseImportFile, 
  ImportParseResult, 
  ProcessedImportRecord, 
  ImportRecordError 
} from '../lib/importParser';

declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: any) => jsPDF;
  }
}

export default function ImportExport() {
  const store = useStore();
  const [activeTab, setActiveTab] = useState<'export' | 'import'>('export');
  const [isProcessing, setIsProcessing] = useState(false);
  const [progress, setProgress] = useState(0);
  const [statusMsg, setStatusMsg] = useState('');
  
  // Import States
  const [parseResult, setParseResult] = useState<ImportParseResult | null>(null);
  const [importPreview, setImportPreview] = useState(false);
  const [skipDuplicates, setSkipDuplicates] = useState(true);
  const [statusFilter, setStatusFilter] = useState<'all' | 'valid' | 'duplicate' | 'invalid'>('all');
  const [importErrorMsg, setImportErrorMsg] = useState<string | null>(null);
  const [importSuccessSummary, setImportSuccessSummary] = useState<{
    imported: number;
    skipped: number;
    failed: number;
  } | null>(null);

  // Helper function to update progress
  const updateProgress = (val: number, msg: string) => {
    setProgress(val);
    setStatusMsg(msg);
  };

  // -------------------------------------------------------------
  // EXPORT LOGIC
  // -------------------------------------------------------------

  const generatePDF = async () => {
    setIsProcessing(true);
    updateProgress(20, 'Initializing PDF generator...');
    
    setTimeout(() => {
      try {
        const doc = new jsPDF();
        updateProgress(50, 'Adding report content...');
        
        doc.setFontSize(22);
        doc.text('SmartLedger Financial Report', 14, 22);
        
        doc.setFontSize(11);
        doc.text(`Generated: ${formatDateTime(new Date().toISOString(), store.generalSettings?.timezone)}`, 14, 30);
        
        doc.setFontSize(14);
        doc.text('Summary', 14, 45);
        
        doc.setFontSize(11);
        doc.text(`Current Balance: ₹${store.currentBalance.toLocaleString()}`, 14, 55);
        doc.text(`Total Income: ₹${store.totalReceived.toLocaleString()}`, 14, 62);
        doc.text(`Total Expenses: ₹${store.totalSent.toLocaleString()}`, 14, 69);
        doc.text(`Total Savings: ₹${(store.totalReceived - store.totalSent).toLocaleString()}`, 14, 76);
        doc.text(`Pending Amount: ₹${store.totalPending.toLocaleString()}`, 14, 83);
        
        updateProgress(70, 'Adding transaction table...');
        const tableData = store.transactions.map(t => [
          formatDate(t.type === 'pending' ? (t as PendingMoney).dueDate : (t as any).date, store.generalSettings?.timezone),
          t.type.toUpperCase(),
          t.personName,
          t.type === 'pending' ? (t as PendingMoney).reason : (t as any).purpose,
          `Rs ${t.amount.toLocaleString()}`,
          t.type === 'pending' ? (t as PendingMoney).status : 'COMPLETED'
        ]);
        
        doc.autoTable({
          startY: 95,
          head: [['Date', 'Type', 'Person/Entity', 'Description', 'Amount', 'Status']],
          body: tableData,
          theme: 'striped',
          styles: { fontSize: 9 },
          headStyles: { fillColor: [79, 70, 229] }
        });
        
        doc.setFontSize(10);
        doc.text('Generated by SmartLedger', 14, doc.internal.pageSize.height - 10);
        
        updateProgress(90, 'Saving PDF...');
        doc.save('SmartLedger_Financial_Report.pdf');
        
        updateProgress(100, 'Done!');
        setTimeout(() => setIsProcessing(false), 1000);
      } catch (err) {
        console.error(err);
        updateProgress(0, 'Export failed');
        setIsProcessing(false);
      }
    }, 500);
  };

  const generateExcel = async () => {
    setIsProcessing(true);
    updateProgress(30, 'Formatting Excel sheets...');
    
    try {
      const { generateAdvancedExcel } = await import('../lib/excelExport');
      const summary = {
        currentBalance: store.currentBalance,
        totalReceived: store.totalReceived,
        totalSent: store.totalSent,
        totalPending: store.totalPending
      };
      await generateAdvancedExcel(store.transactions, summary);
      
      updateProgress(100, 'Done!');
      setTimeout(() => setIsProcessing(false), 1000);
    } catch (err) {
      console.error(err);
      updateProgress(0, 'Export failed');
      setIsProcessing(false);
    }
  };

  const generateCSV = () => {
    setIsProcessing(true);
    updateProgress(50, 'Generating CSV...');
    
    setTimeout(() => {
      const data = store.transactions.map(t => ({
        Date: t.type === 'pending' ? (t as PendingMoney).dueDate : (t as any).date,
        Type: t.type,
        Category: 'General',
        Description: t.type === 'pending' ? (t as PendingMoney).reason : (t as any).purpose,
        Amount: t.amount,
        Status: t.type === 'pending' ? (t as PendingMoney).status : 'Completed',
        Person: t.personName,
        'Payment Method': 'Bank Transfer'
      }));
      
      const csv = Papa.unparse(data);
      const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
      saveAs(blob, 'SmartLedger_Transactions.csv');
      
      updateProgress(100, 'Done!');
      setTimeout(() => setIsProcessing(false), 1000);
    }, 500);
  };

  const createBackup = () => {
    setIsProcessing(true);
    updateProgress(50, 'Generating secure backup JSON...');
    
    setTimeout(() => {
      const backupData = JSON.stringify({
        isSetupComplete: store.isSetupComplete,
        startingBalance: store.startingBalance,
        transactions: store.transactions,
        securitySettings: store.securitySettings
      }, null, 2);
      
      const blob = new Blob([backupData], { type: 'application/json' });
      saveAs(blob, `SmartLedger_Backup_${new Date().toISOString().split('T')[0]}.json`);
      
      updateProgress(100, 'Backup Complete!');
      setTimeout(() => setIsProcessing(false), 1000);
    }, 500);
  };

  const generateZip = async () => {
    setIsProcessing(true);
    updateProgress(20, 'Preparing ZIP archive...');
    
    try {
      const zip = new JSZip();
      
      // JSON Backup
      const backupData = JSON.stringify({
        isSetupComplete: store.isSetupComplete,
        startingBalance: store.startingBalance,
        transactions: store.transactions,
        securitySettings: store.securitySettings
      }, null, 2);
      zip.file('Backup.json', backupData);
      
      // CSV
      updateProgress(40, 'Adding CSV records...');
      const csvData = store.transactions.map(t => ({
        Date: t.type === 'pending' ? (t as PendingMoney).dueDate : (t as any).date,
        Type: t.type,
        Category: 'General',
        Description: t.type === 'pending' ? (t as PendingMoney).reason : (t as any).purpose,
        Amount: t.amount,
        Status: t.type === 'pending' ? (t as PendingMoney).status : 'Completed',
        Person: t.personName,
        'Payment Method': 'Bank Transfer'
      }));
      zip.file('Transactions.csv', Papa.unparse(csvData));
      
      updateProgress(80, 'Compressing archive...');
      const content = await zip.generateAsync({ type: 'blob' });
      saveAs(content, 'SmartLedger_Complete_Export.zip');
      
      updateProgress(100, 'Done!');
      setTimeout(() => setIsProcessing(false), 1000);
    } catch (err) {
      console.error(err);
      updateProgress(0, 'Failed to create ZIP');
      setIsProcessing(false);
    }
  };


  // -------------------------------------------------------------
  // IMPORT LOGIC
  // -------------------------------------------------------------

  const handleFileProcess = useCallback(async (file: File) => {
    if (!file) return;

    setImportErrorMsg(null);
    setImportSuccessSummary(null);
    setIsProcessing(true);
    updateProgress(10, 'Initializing file parser...');

    try {
      const result = await parseImportFile(
        file, 
        store.transactions, 
        (pct, msg) => updateProgress(pct, msg)
      );

      if (result.totalCount === 0) {
        throw new Error('File contains no records or rows to import.');
      }

      setParseResult(result);
      setImportPreview(true);
      setStatusFilter('all');
    } catch (err: any) {
      console.error('File import parsing error:', err);
      setImportErrorMsg(err?.message || 'Failed to parse file. Please verify format.');
    } finally {
      setIsProcessing(false);
    }
  }, [store.transactions]);

  const onDrop = useCallback((acceptedFiles: File[]) => {
    if (acceptedFiles && acceptedFiles.length > 0) {
      handleFileProcess(acceptedFiles[0]);
    }
  }, [handleFileProcess]);

  const { getRootProps, getInputProps, isDragActive } = useDropzone({ 
    onDrop,
    multiple: false
  });

  const filteredPreviewRecords = useMemo(() => {
    if (!parseResult) return [];
    if (statusFilter === 'all') return parseResult.records;
    return parseResult.records.filter(r => r.status === statusFilter);
  }, [parseResult, statusFilter]);

  const confirmImport = () => {
    if (!parseResult || !parseResult.records.length) return;

    setIsProcessing(true);
    updateProgress(20, 'Preparing transactions for import...');

    setTimeout(() => {
      const recordsToImport = parseResult.records.filter(r => {
        if (r.status === 'invalid') return false;
        if (r.status === 'duplicate' && skipDuplicates) return false;
        return true;
      });

      if (recordsToImport.length === 0) {
        setIsProcessing(false);
        setImportErrorMsg('No eligible records to import based on your current settings.');
        return;
      }

      updateProgress(60, 'Saving transactions to database...');

      const newTransactions = recordsToImport.map(r => r.transaction);

      // Merge with store state
      const updatedTransactions = [...newTransactions, ...store.transactions];

      store.importData({
        ...store,
        transactions: updatedTransactions
      });

      const skippedCount = parseResult.totalCount - recordsToImport.length;

      updateProgress(100, 'Import completed successfully!');

      setTimeout(() => {
        setIsProcessing(false);
        setImportPreview(false);
        setImportSuccessSummary({
          imported: newTransactions.length,
          skipped: skippedCount,
          failed: parseResult.invalidCount
        });
        setParseResult(null);
      }, 1000);
    }, 500);
  };

  const downloadErrorReport = () => {
    if (!parseResult || parseResult.errors.length === 0) return;

    const errorCsvData = parseResult.errors.map(err => ({
      'Row Number': err.rowNumber,
      'Failure Reason': err.reason,
      'Raw Record Data': JSON.stringify(err.rawRecord || {})
    }));

    const csvContent = Papa.unparse(errorCsvData);
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    saveAs(blob, `Import_Error_Report_${new Date().toISOString().split('T')[0]}.csv`);
  };

  const resetImportState = () => {
    setParseResult(null);
    setImportPreview(false);
    setImportErrorMsg(null);
  };

  return (
    <div className="w-full flex flex-col gap-6">
      <header className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold text-white tracking-tight">Import & Export</h1>
          <p className="text-neutral-400 text-sm mt-1">Manage, backup, and import financial ledger records securely</p>
        </div>
      </header>

      {/* Custom Navigation Tabs */}
      <div className="flex gap-2 bg-[#0a0b10]/80 p-1.5 rounded-2xl w-fit border border-white/10 backdrop-blur-xl">
        <button
          onClick={() => setActiveTab('export')}
          className={`px-6 py-2.5 rounded-xl text-sm font-semibold transition-all ${
            activeTab === 'export' ? 'bg-emerald-600 text-white shadow-lg shadow-emerald-600/30' : 'text-neutral-400 hover:text-white'
          }`}
        >
          Export & Backup
        </button>
        <button
          onClick={() => setActiveTab('import')}
          className={`px-6 py-2.5 rounded-xl text-sm font-semibold transition-all ${
            activeTab === 'import' ? 'bg-emerald-600 text-white shadow-lg shadow-emerald-600/30' : 'text-neutral-400 hover:text-white'
          }`}
        >
          Import Data
        </button>
      </div>

      <AnimatePresence mode="wait">
        {activeTab === 'export' ? (
          <motion.div
            key="export"
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -10 }}
            className="grid grid-cols-1 md:grid-cols-2 gap-6"
          >
            {/* Download Everything */}
            <div className="col-span-1 md:col-span-2 bg-gradient-to-r from-emerald-500/10 to-teal-500/10 border border-emerald-500/30 rounded-3xl p-8 relative overflow-hidden flex flex-col md:flex-row items-center justify-between gap-6 group backdrop-blur-xl">
              <div className="absolute top-0 right-0 w-64 h-64 bg-emerald-500/10 rounded-full blur-[80px] group-hover:bg-emerald-500/20 transition-all duration-500"></div>
              
              <div className="relative z-10 flex-1">
                <div className="flex items-center gap-3 mb-2">
                  <FileArchive className="text-emerald-400" size={24} />
                  <h2 className="text-2xl font-bold text-white">One-Click Complete Export</h2>
                </div>
                <p className="text-neutral-300 text-sm font-normal max-w-xl">
                  Get a comprehensive ZIP archive containing your financial reports in PDF, all ledger transactions in Excel & CSV formats, and a full system backup JSON.
                </p>
              </div>

              <button 
                onClick={generateZip}
                disabled={isProcessing}
                className="relative z-10 flex items-center justify-center gap-2 bg-emerald-600 hover:bg-emerald-500 text-white px-8 py-4 rounded-2xl font-bold transition-all shadow-lg shadow-emerald-600/30 w-full md:w-auto disabled:opacity-50 shrink-0"
              >
                <Download size={20} />
                Download Everything
              </button>
            </div>

            {/* Individual Exports */}
            <div className="bg-white/5 border border-white/10 backdrop-blur-xl rounded-3xl p-6 hover:border-white/20 transition-all">
              <div className="flex items-center gap-3 mb-6">
                <div className="w-10 h-10 bg-red-500/10 border border-red-500/20 rounded-xl flex items-center justify-center text-red-400">
                  <FileText size={20} />
                </div>
                <div>
                  <h3 className="text-lg font-bold text-white">Export as PDF</h3>
                  <p className="text-xs text-neutral-400">Printable official financial report</p>
                </div>
              </div>
              <button onClick={generatePDF} disabled={isProcessing} className="w-full flex items-center justify-center gap-2 bg-white/5 hover:bg-white/10 text-white py-3 rounded-xl transition-colors border border-white/10 font-semibold text-sm">
                Generate PDF <ArrowRight size={16} className="text-neutral-400" />
              </button>
            </div>

            <div className="bg-white/5 border border-white/10 backdrop-blur-xl rounded-3xl p-6 hover:border-white/20 transition-all">
              <div className="flex items-center gap-3 mb-6">
                <div className="w-10 h-10 bg-emerald-500/10 border border-emerald-500/20 rounded-xl flex items-center justify-center text-emerald-400">
                  <FileSpreadsheet size={20} />
                </div>
                <div>
                  <h3 className="text-lg font-bold text-white">Export as Excel</h3>
                  <p className="text-xs text-neutral-400">Formatted spreadsheets (.xlsx)</p>
                </div>
              </div>
              <button onClick={generateExcel} disabled={isProcessing} className="w-full flex items-center justify-center gap-2 bg-white/5 hover:bg-white/10 text-white py-3 rounded-xl transition-colors border border-white/10 font-semibold text-sm">
                Generate Excel <ArrowRight size={16} className="text-neutral-400" />
              </button>
            </div>

            <div className="bg-white/5 border border-white/10 backdrop-blur-xl rounded-3xl p-6 hover:border-white/20 transition-all">
              <div className="flex items-center gap-3 mb-6">
                <div className="w-10 h-10 bg-blue-500/10 border border-blue-500/20 rounded-xl flex items-center justify-center text-blue-400">
                  <FileText size={20} />
                </div>
                <div>
                  <h3 className="text-lg font-bold text-white">Export as CSV</h3>
                  <p className="text-xs text-neutral-400">Raw transaction data</p>
                </div>
              </div>
              <button onClick={generateCSV} disabled={isProcessing} className="w-full flex items-center justify-center gap-2 bg-white/5 hover:bg-white/10 text-white py-3 rounded-xl transition-colors border border-white/10 font-semibold text-sm">
                Generate CSV <ArrowRight size={16} className="text-neutral-400" />
              </button>
            </div>

            <div className="bg-white/5 border border-white/10 backdrop-blur-xl rounded-3xl p-6 hover:border-white/20 transition-all relative overflow-hidden">
              <div className="flex items-center gap-3 mb-6 relative z-10">
                <div className="w-10 h-10 bg-amber-500/10 border border-amber-500/20 rounded-xl flex items-center justify-center text-amber-400">
                  <FileJson size={20} />
                </div>
                <div>
                  <h3 className="text-lg font-bold text-white">Create System Backup</h3>
                  <p className="text-xs text-neutral-400">Full encrypted JSON snapshot</p>
                </div>
              </div>
              <button onClick={createBackup} disabled={isProcessing} className="w-full relative z-10 flex items-center justify-center gap-2 bg-amber-500/10 hover:bg-amber-500/20 text-amber-400 py-3 rounded-xl transition-colors border border-amber-500/20 font-semibold text-sm">
                Create Backup <ArrowRight size={16} />
              </button>
            </div>

          </motion.div>
        ) : (
          <motion.div
            key="import"
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -10 }}
            className="space-y-6"
          >
            {/* Import Success Notification */}
            {importSuccessSummary && (
              <div className="p-6 bg-emerald-500/10 border border-emerald-500/30 rounded-3xl flex items-start justify-between gap-4">
                <div className="flex items-start gap-3">
                  <CheckCircle2 size={24} className="text-emerald-400 shrink-0 mt-0.5" />
                  <div>
                    <h3 className="text-emerald-400 font-bold text-lg">Import Completed Successfully!</h3>
                    <p className="text-neutral-300 text-sm mt-1">
                      Successfully imported <strong className="text-white">{importSuccessSummary.imported}</strong> ledger records. 
                      Skipped <strong className="text-amber-400">{importSuccessSummary.skipped}</strong> duplicate or invalid records.
                    </p>
                  </div>
                </div>
                <button onClick={() => setImportSuccessSummary(null)} className="p-1 text-neutral-400 hover:text-white">
                  <X size={20} />
                </button>
              </div>
            )}

            {/* Import Error Message */}
            {importErrorMsg && (
              <div className="p-5 bg-red-500/10 border border-red-500/30 rounded-3xl flex items-center justify-between gap-4">
                <div className="flex items-center gap-3">
                  <AlertCircle size={22} className="text-red-400 shrink-0" />
                  <span className="text-red-300 text-sm font-medium">{importErrorMsg}</span>
                </div>
                <button onClick={() => setImportErrorMsg(null)} className="p-1 text-neutral-400 hover:text-white">
                  <X size={18} />
                </button>
              </div>
            )}

            {importPreview && parseResult ? (
              <div className="bg-white/5 border border-white/10 backdrop-blur-xl rounded-3xl p-6 md:p-8 space-y-6">
                {/* Header & Controls */}
                <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4 pb-6 border-b border-white/10">
                  <div>
                    <h3 className="text-2xl font-bold text-white">Import Records Preview</h3>
                    <p className="text-xs text-neutral-400 mt-1">
                      File: <span className="text-emerald-400 font-mono font-bold">{parseResult.fileName}</span> ({parseResult.fileType.toUpperCase()})
                    </p>
                  </div>

                  <div className="flex flex-wrap items-center gap-3">
                    <button 
                      onClick={resetImportState} 
                      className="px-4 py-2.5 rounded-xl bg-white/5 hover:bg-white/10 text-neutral-300 hover:text-white border border-white/10 text-sm font-semibold transition-colors"
                    >
                      Cancel / Re-upload
                    </button>
                    {parseResult.errors.length > 0 && (
                      <button 
                        onClick={downloadErrorReport} 
                        className="px-4 py-2.5 rounded-xl bg-red-500/10 hover:bg-red-500/20 text-red-400 border border-red-500/30 text-sm font-semibold transition-colors flex items-center gap-2"
                      >
                        <FileX size={16} /> Download Error Log ({parseResult.errors.length})
                      </button>
                    )}
                    <button 
                      onClick={confirmImport} 
                      disabled={isProcessing || parseResult.validCount === 0} 
                      className="px-6 py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-500 disabled:opacity-50 text-white font-bold text-sm shadow-lg shadow-emerald-600/30 transition-all flex items-center gap-2"
                    >
                      <CheckCircle2 size={18} /> Confirm & Commit Import
                    </button>
                  </div>
                </div>

                {/* Summary Metrics Cards */}
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
                  <div className="p-4 bg-black/40 border border-white/10 rounded-2xl">
                    <div className="text-xs font-semibold text-neutral-400 uppercase tracking-wider">Total Records</div>
                    <div className="text-2xl font-bold text-white mt-1">{parseResult.totalCount}</div>
                  </div>

                  <div className="p-4 bg-emerald-500/10 border border-emerald-500/20 rounded-2xl">
                    <div className="text-xs font-semibold text-emerald-400 uppercase tracking-wider">Valid Records</div>
                    <div className="text-2xl font-bold text-emerald-400 mt-1">{parseResult.validCount}</div>
                  </div>

                  <div className="p-4 bg-amber-500/10 border border-amber-500/20 rounded-2xl">
                    <div className="text-xs font-semibold text-amber-400 uppercase tracking-wider">Duplicates</div>
                    <div className="text-2xl font-bold text-amber-400 mt-1">{parseResult.duplicateCount}</div>
                  </div>

                  <div className="p-4 bg-red-500/10 border border-red-500/20 rounded-2xl">
                    <div className="text-xs font-semibold text-red-400 uppercase tracking-wider">Invalid Rows</div>
                    <div className="text-2xl font-bold text-red-400 mt-1">{parseResult.invalidCount}</div>
                  </div>
                </div>

                {/* Duplicate Settings Toggle */}
                <div className="p-4 bg-black/40 border border-white/10 rounded-2xl flex flex-col sm:flex-row sm:items-center justify-between gap-3 text-sm">
                  <label className="flex items-center gap-3 cursor-pointer select-none">
                    <input 
                      type="checkbox" 
                      checked={skipDuplicates} 
                      onChange={e => setSkipDuplicates(e.target.checked)}
                      className="w-4 h-4 rounded text-emerald-600 focus:ring-emerald-500 bg-black/60 border-white/20 cursor-pointer"
                    />
                    <div>
                      <span className="font-semibold text-white">Skip Duplicate Records</span>
                      <p className="text-xs text-neutral-400">Records matching date, amount, and name will not be imported</p>
                    </div>
                  </label>

                  {/* Filter Pills */}
                  <div className="flex items-center gap-1.5 bg-white/5 p-1 rounded-xl border border-white/10 text-xs">
                    {(['all', 'valid', 'duplicate', 'invalid'] as const).map(mode => (
                      <button
                        key={mode}
                        onClick={() => setStatusFilter(mode)}
                        className={`px-3 py-1.5 rounded-lg font-semibold capitalize transition-colors ${
                          statusFilter === mode 
                            ? 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/30' 
                            : 'text-neutral-400 hover:text-white'
                        }`}
                      >
                        {mode}
                      </button>
                    ))}
                  </div>
                </div>

                {/* Scrollable Records Table */}
                <div className="bg-black/40 rounded-2xl border border-white/10 overflow-hidden">
                  <div className="max-h-[450px] overflow-y-auto relative">
                    <table className="w-full text-left border-collapse">
                      <thead className="sticky top-0 bg-[#0c0c0c] z-10 border-b border-white/10">
                        <tr className="text-neutral-400 text-xs font-semibold uppercase tracking-wider">
                          <th className="py-3 px-4">Row #</th>
                          <th className="py-3 px-4">Date</th>
                          <th className="py-3 px-4">Type</th>
                          <th className="py-3 px-4">Customer / Added By</th>
                          <th className="py-3 px-4">Amount (₹)</th>
                          <th className="py-3 px-4">Category / Notes</th>
                          <th className="py-3 px-4 text-right">Status</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-white/5 text-sm">
                        {filteredPreviewRecords.length > 0 ? (
                          filteredPreviewRecords.map((item) => {
                            const isVal = item.status === 'valid';
                            const isDup = item.status === 'duplicate';
                            const isInv = item.status === 'invalid';
                            const tx = item.transaction;

                            return (
                              <tr key={item.rowNumber} className="hover:bg-white/[0.03] transition-colors">
                                <td className="py-3.5 px-4 font-mono text-xs text-neutral-500">
                                  #{item.rowNumber}
                                </td>
                                <td className="py-3.5 px-4 text-neutral-300 font-mono text-xs whitespace-nowrap">
                                  {isInv ? '-' : (tx as any).date || (tx as any).dueDate || 'N/A'}
                                </td>
                                <td className="py-3.5 px-4 whitespace-nowrap">
                                  {isInv ? '-' : (
                                    <span className={`px-2.5 py-0.5 rounded-md text-[11px] font-bold uppercase tracking-wider ${
                                      tx.type === 'received' ? 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/20' :
                                      tx.type === 'sent' ? 'bg-red-500/10 text-red-400 border border-red-500/20' :
                                      'bg-amber-500/10 text-amber-400 border border-amber-500/20'
                                    }`}>
                                      {tx.type}
                                    </span>
                                  )}
                                </td>
                                <td className="py-3.5 px-4 font-bold text-white whitespace-nowrap">
                                  {isInv ? (item.rawRecord?.Name || item.rawRecord?.Person || 'Invalid') : tx.personName}
                                </td>
                                <td className="py-3.5 px-4 font-bold text-emerald-400 whitespace-nowrap">
                                  {isInv ? '-' : `₹${(Number(tx.amount) || 0).toLocaleString('en-IN')}`}
                                </td>
                                <td className="py-3.5 px-4 text-neutral-300 text-xs max-w-xs truncate">
                                  {isInv ? '-' : ((tx as any).purpose || (tx as any).reason || (tx as any).category || '-')}
                                </td>
                                <td className="py-3.5 px-4 text-right whitespace-nowrap">
                                  {isVal && (
                                    <span className="px-2.5 py-1 rounded-full text-xs font-bold bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 inline-flex items-center gap-1">
                                      <Check size={12} /> Valid
                                    </span>
                                  )}
                                  {isDup && (
                                    <span className="px-2.5 py-1 rounded-full text-xs font-bold bg-amber-500/10 text-amber-400 border border-amber-500/20 inline-flex items-center gap-1" title="Matches existing record">
                                      <AlertTriangle size={12} /> Duplicate
                                    </span>
                                  )}
                                  {isInv && (
                                    <span className="px-2.5 py-1 rounded-full text-xs font-bold bg-red-500/10 text-red-400 border border-red-500/20 inline-flex items-center gap-1" title={item.errorReason}>
                                      <AlertCircle size={12} /> Invalid
                                    </span>
                                  )}
                                </td>
                              </tr>
                            );
                          })
                        ) : (
                          <tr>
                            <td colSpan={7} className="text-center py-12 text-neutral-400">
                              No records match filter "{statusFilter}".
                            </td>
                          </tr>
                        )}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            ) : (
              <div 
                {...getRootProps()} 
                className={`border-2 border-dashed rounded-3xl p-12 text-center transition-all cursor-pointer ${
                  isDragActive 
                    ? 'border-emerald-500 bg-emerald-500/10' 
                    : 'border-white/10 hover:border-emerald-500/40 hover:bg-white/[0.02]'
                }`}
              >
                <input {...getInputProps()} />
                <div className="w-20 h-20 bg-gradient-to-tr from-emerald-600/20 to-teal-500/20 border border-emerald-500/30 rounded-3xl mx-auto flex items-center justify-center mb-6 shadow-xl shadow-emerald-500/10">
                  <UploadCloud size={36} className="text-emerald-400" />
                </div>
                <h3 className="text-2xl font-bold text-white mb-2">
                  {isDragActive ? 'Drop file to process' : 'Drag & Drop CSV, Excel, or JSON File'}
                </h3>
                <p className="text-neutral-400 text-sm mb-6 max-w-md mx-auto">
                  Automatically parses and maps <strong className="text-white">.csv</strong>, <strong className="text-white">.xlsx</strong>, <strong className="text-white">.xls</strong>, and <strong className="text-white">.json</strong> bank or ledger statements.
                </p>
                <button 
                  type="button" 
                  className="bg-emerald-600 hover:bg-emerald-500 text-white px-8 py-3 rounded-xl font-bold text-sm transition-all shadow-lg shadow-emerald-600/20 border border-emerald-500/30"
                >
                  Browse Files
                </button>
              </div>
            )}

            {/* Security Banner */}
            <div className="bg-blue-500/10 border border-blue-500/20 rounded-2xl p-5 flex items-start gap-4">
              <Info className="text-blue-400 shrink-0 mt-0.5" size={20} />
              <div>
                <h4 className="text-blue-400 font-bold mb-1">Local Processing & Deduplication Security</h4>
                <p className="text-xs text-blue-200/80 font-normal leading-relaxed">
                  All imported files are parsed locally on your device. Column headers like <code className="bg-blue-900/50 px-1 py-0.5 rounded text-blue-300">Date</code>, <code className="bg-blue-900/50 px-1 py-0.5 rounded text-blue-300">Amount</code>, <code className="bg-blue-900/50 px-1 py-0.5 rounded text-blue-300">Category</code>, <code className="bg-blue-900/50 px-1 py-0.5 rounded text-blue-300">Person/Customer</code>, and <code className="bg-blue-900/50 px-1 py-0.5 rounded text-blue-300">Type</code> are auto-mapped regardless of letter casing or browser MIME formatting.
                </p>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Global Processing Progress Overlay */}
      <AnimatePresence>
        {isProcessing && (
          <motion.div 
            initial={{ opacity: 0 }} 
            animate={{ opacity: 1 }} 
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 bg-black/80 backdrop-blur-md flex items-center justify-center p-4"
          >
            <div className="bg-[#121212] border border-white/10 rounded-3xl p-8 max-w-sm w-full text-center shadow-2xl flex flex-col items-center">
              <RefreshCcw size={40} className="text-emerald-400 animate-spin mb-6" />
              <h3 className="text-lg font-bold text-white mb-2">{statusMsg || 'Processing Data...'}</h3>
              <div className="w-full h-2 bg-white/10 rounded-full overflow-hidden mt-4">
                <motion.div 
                  className="h-full bg-gradient-to-r from-emerald-500 to-teal-400"
                  initial={{ width: 0 }}
                  animate={{ width: `${progress}%` }}
                  transition={{ ease: "linear", duration: 0.15 }}
                />
              </div>
              <span className="text-xs font-mono text-neutral-400 mt-2">{progress}%</span>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

    </div>
  );
}
