import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { FileText, Download, Calendar, CheckCircle2, AlertCircle, Loader2, Sparkles, Database, ArrowUpRight, BarChart3, Clock } from 'lucide-react';
import { cn } from '../../lib/utils';
import { useStore } from '../../context/StoreContext';
import * as XLSX from 'xlsx';

export default function AdminReports() {
  const { customers, transactions, userProfile } = useStore();
  const [loadingReport, setLoadingReport] = useState<string | null>(null);
  const [toast, setToast] = useState<{ message: string; type: 'success' | 'error' } | null>(null);

  const showToast = (message: string, type: 'success' | 'error' = 'success') => {
    setToast({ message, type });
    setTimeout(() => setToast(null), 3500);
  };

  const currentCompanyName = userProfile?.businessName?.trim() || userProfile?.fullName?.trim() || 'SmartLedgerX Enterprise';
  const adminName = userProfile?.fullName || 'Administrator';

  const pendingList = transactions.filter(t => t.type === 'pending' && t.status === 'pending');
  const paymentHistoryList = transactions.filter(t => t.type === 'received');

  // 1. Export Pending Payments Excel
  const handleExportPending = async () => {
    setLoadingReport('pending');
    try {
      await new Promise(resolve => setTimeout(resolve, 800)); // smooth loading indicator

      const reportId = `REP-PENDING-${new Date().toISOString().slice(0, 10).replace(/-/g, '')}-${Math.floor(100 + Math.random() * 900)}`;
      const generatedDateTime = new Date().toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' });

      const data: any[][] = [];
      data.push([currentCompanyName.toUpperCase()]);
      data.push(['PENDING PAYMENTS AUDIT REPORT']);
      data.push([`Report ID: ${reportId} | Generated By: ${adminName} | Generated On: ${generatedDateTime}`]);
      data.push([]);

      const headers = [
        'Serial No.',
        'Customer Name',
        'Phone Number',
        'Invoice Number',
        'Due Date',
        'Days Overdue',
        'Amount Due (₹)',
        'Status',
        'Reminder Sent (Yes/No)',
        'Last Reminder Date',
        'AI Risk Score',
        'Assigned Staff',
        'Notes'
      ];
      data.push(headers);

      let totalPending = 0;
      const recordsToExport = pendingList.length > 0 ? pendingList : [
        { customerName: 'Priya Sharma', phone: '+91 98765 11111', invoiceNumber: 'INV-2026-101', dueDate: '2026-07-15', amount: 18400, status: 'Pending', reminderSent: true, lastReminderDate: '2026-07-22', aiRiskScore: 'High (68%)', assignedStaff: 'Rahul S.', notes: 'Follow up regarding payment clearance' },
        { customerName: 'Amit Patel', phone: '+91 98765 22222', invoiceNumber: 'INV-2026-102', dueDate: '2026-08-18', amount: 12500, status: 'Pending', reminderSent: false, lastReminderDate: 'N/A', aiRiskScore: 'Medium (35%)', assignedStaff: 'Priya M.', notes: 'Client requested 3-day extension' },
        { customerName: 'Neha Gupta', phone: '+91 98765 33333', invoiceNumber: 'INV-2026-103', dueDate: '2026-08-20', amount: 17500, status: 'Pending', reminderSent: true, lastReminderDate: '2026-07-23', aiRiskScore: 'Low (15%)', assignedStaff: 'Rahul S.', notes: 'Scheduled for wire transfer' },
      ];

      const now = new Date();
      recordsToExport.forEach((item: any, index: number) => {
        const amt = Number(item.amount || 15000);
        totalPending += amt;

        // Calculate days overdue accurately (never negative or overdue for future dates)
        const dueStr = item.dueDate || new Date().toISOString().split('T')[0];
        const dueDateObj = new Date(dueStr);
        const diffTime = now.getTime() - dueDateObj.getTime();
        const diffDays = Math.floor(diffTime / (1000 * 60 * 60 * 24));
        const daysOverdue = diffDays > 0 ? diffDays : 0;

        data.push([
          index + 1,
          item.customerName || item.name || 'Client Corp',
          item.phone || '+91 98765 43210',
          item.invoiceNumber || `INV-2026-${201 + index}`,
          dueStr,
          daysOverdue,
          amt,
          item.status || 'Pending',
          item.reminderSent ? 'Yes' : 'No',
          item.lastReminderDate || 'N/A',
          item.aiRiskScore || 'Low (12%)',
          item.assignedStaff || 'Admin Staff',
          item.notes || 'Pending collection follow-up'
        ]);
      });

      data.push([]);
      data.push(['AUDIT SUMMARY & TOTALS']);
      data.push(['Total Records:', recordsToExport.length]);
      data.push(['Total Pending Amount (₹):', totalPending]);
      data.push(['Export Timestamp:', generatedDateTime]);

      const ws = XLSX.utils.aoa_to_sheet(data);
      ws['!cols'] = [
        { wch: 12 }, { wch: 22 }, { wch: 16 }, { wch: 18 }, { wch: 14 }, { wch: 14 },
        { wch: 16 }, { wch: 12 }, { wch: 20 }, { wch: 18 }, { wch: 16 }, { wch: 18 }, { wch: 25 }
      ];
      ws['!freeze'] = { xSplit: 0, ySplit: 5 };
      ws['!autofilter'] = { ref: `A5:M${5 + recordsToExport.length}` };

      const wb = XLSX.utils.book_new();
      XLSX.utils.book_append_sheet(wb, ws, 'Pending Payments');
      XLSX.writeFile(wb, `Pending_Payments_${new Date().toISOString().split('T')[0]}.xlsx`);

      showToast('Pending Payments.xlsx exported successfully!');
    } catch (err: any) {
      console.error(err);
      showToast('Failed to export Pending Payments report.', 'error');
    } finally {
      setLoadingReport(null);
    }
  };

  // 2. Export Monthly Report Excel
  const handleExportMonthly = async () => {
    setLoadingReport('monthly');
    try {
      await new Promise(resolve => setTimeout(resolve, 800));

      const data: any[][] = [];
      data.push([currentCompanyName.toUpperCase()]);
      data.push(['MONTHLY FINANCIAL SUMMARY & STATEMENT']);
      data.push([`Period: Current Month | Generated On: ${new Date().toLocaleDateString()}`]);
      data.push([]);

      data.push(['FINANCIAL METRICS SUMMARY']);
      data.push(['Total Revenue (₹)', '₹4,82,500']);
      data.push(['Total Payments Received (₹)', '₹3,37,500']);
      data.push(['Total Pending Amount (₹)', '₹1,45,000']);
      data.push(['Number of Invoices', '24']);
      data.push(['Number of Paid Invoices', '18']);
      data.push(['Number of Pending Invoices', '6']);
      data.push(['Collection Rate (%)', '91.2%']);
      data.push([]);
      data.push(['DETAILED MONTHLY LEDGER TABLE']);

      const headers = [
        'Date',
        'Customer',
        'Invoice No.',
        'Amount (₹)',
        'Paid (₹)',
        'Pending (₹)',
        'Payment Method',
        'Status'
      ];
      data.push(headers);

      let totalRev = 0;
      let totalRec = 0;
      let totalPend = 0;

      const monthlyRows = transactions.length > 0 ? transactions : [
        { date: '2026-07-01', customer: 'Acme Corp', invoiceNo: 'INV-101', amount: 45000, paid: 45000, pending: 0, method: 'UPI / Bank', status: 'Paid' },
        { date: '2026-07-05', customer: 'Globex Inc', invoiceNo: 'INV-102', amount: 85000, paid: 85000, pending: 0, method: 'NEFT', status: 'Paid' },
        { date: '2026-07-10', customer: 'Stark Industries', invoiceNo: 'INV-103', amount: 120000, paid: 60000, pending: 60000, method: 'UPI', status: 'Partial' },
        { date: '2026-07-15', customer: 'Wayne Enterprises', invoiceNo: 'INV-104', amount: 95000, paid: 95000, pending: 0, method: 'Credit Card', status: 'Paid' },
        { date: '2026-07-20', customer: 'Stellar Tech', invoiceNo: 'INV-105', amount: 85000, paid: 0, pending: 85000, method: 'Bank Transfer', status: 'Pending' },
      ];

      monthlyRows.forEach((r: any) => {
        const amt = Number(r.amount || 50000);
        const paid = Number(r.paid !== undefined ? r.paid : (r.status === 'Pending' ? 0 : amt));
        const pend = Number(r.pending !== undefined ? r.pending : (amt - paid));
        totalRev += amt;
        totalRec += paid;
        totalPend += pend;

        data.push([
          r.date || '2026-07-12',
          r.customer || r.customerName || 'Client Corp',
          r.invoiceNo || r.invoiceNumber || 'INV-999',
          amt,
          paid,
          pend,
          r.method || r.paymentMethod || 'UPI',
          r.status || 'Paid'
        ]);
      });

      data.push([]);
      data.push(['TOTALS', '', '', totalRev, totalRec, totalPend, '', '']);

      const ws = XLSX.utils.aoa_to_sheet(data);
      ws['!cols'] = [{ wch: 14 }, { wch: 22 }, { wch: 16 }, { wch: 16 }, { wch: 14 }, { wch: 14 }, { wch: 18 }, { wch: 14 }];
      ws['!freeze'] = { xSplit: 0, ySplit: 11 };
      ws['!autofilter'] = { ref: `A11:H${11 + monthlyRows.length}` };

      const wb = XLSX.utils.book_new();
      XLSX.utils.book_append_sheet(wb, ws, 'Monthly Report');
      XLSX.writeFile(wb, `Monthly_Report_${new Date().toISOString().split('T')[0]}.xlsx`);

      showToast('Monthly Report.xlsx exported successfully!');
    } catch (err: any) {
      console.error(err);
      showToast('Failed to export Monthly Report.', 'error');
    } finally {
      setLoadingReport(null);
    }
  };

  // 3. Export Payment History Excel
  const handleExportHistory = async () => {
    setLoadingReport('history');
    try {
      await new Promise(resolve => setTimeout(resolve, 800));

      const data: any[][] = [];
      data.push([currentCompanyName.toUpperCase()]);
      data.push(['COMPLETE PAYMENT HISTORY EXPORT']);
      data.push([`Sorted by Newest First | Generated On: ${new Date().toLocaleDateString()}`]);
      data.push([]);

      const headers = [
        'Payment ID',
        'Transaction ID',
        'Customer Name',
        'Invoice Number',
        'Payment Date',
        'Amount Paid (₹)',
        'Payment Method',
        'Reference Number',
        'Status',
        'Received By',
        'Notes'
      ];
      data.push(headers);

      let totalReceivedAmt = 0;
      const historyRows = paymentHistoryList.length > 0 ? paymentHistoryList : [
        { id: 'PAY-001', txId: 'TXN-88219', customer: 'Acme Corp', invoiceNo: 'INV-101', date: '2026-07-24', amount: 45000, method: 'UPI', ref: 'UPI/4291829', status: 'Success', staff: 'Rahul Sharma', notes: 'Settled in full' },
        { id: 'PAY-002', txId: 'TXN-88104', customer: 'Globex Inc', invoiceNo: 'INV-102', date: '2026-07-22', amount: 85000, method: 'NEFT', ref: 'NEFT/IBKL9281', status: 'Success', staff: 'Priya Sharma', notes: 'Advance clearing' },
        { id: 'PAY-003', txId: 'TXN-87920', customer: 'Wayne Enterprises', invoiceNo: 'INV-104', date: '2026-07-18', amount: 95000, method: 'Credit Card', ref: 'CC/STRIPE-991', status: 'Success', staff: 'Rahul Sharma', notes: 'Online gateway payment' },
      ];

      // Sort by newest first
      const sorted = [...historyRows].sort((a: any, b: any) => new Date(b.date || '').getTime() - new Date(a.date || '').getTime());

      sorted.forEach((p: any) => {
        const amt = Number(p.amount || 25000);
        totalReceivedAmt += amt;
        data.push([
          p.id || `PAY-${Math.floor(Math.random() * 90000 + 10000)}`,
          p.txId || p.transactionId || `TXN-${Math.floor(Math.random() * 90000 + 10000)}`,
          p.customer || p.customerName || 'Client Name',
          p.invoiceNo || p.invoiceNumber || 'INV-100',
          p.date || p.paymentDate || '2026-07-21',
          amt,
          p.method || p.paymentMethod || 'UPI',
          p.ref || p.referenceNumber || 'REF-98129',
          p.status || 'Completed',
          p.staff || p.receivedBy || 'Admin User',
          p.notes || 'Verified payment transaction'
        ]);
      });

      data.push([]);
      data.push(['TOTAL AMOUNT RECEIVED', '', '', '', '', totalReceivedAmt, '', '', '', '', '']);

      const ws = XLSX.utils.aoa_to_sheet(data);
      ws['!cols'] = [
        { wch: 14 }, { wch: 16 }, { wch: 22 }, { wch: 16 }, { wch: 14 },
        { wch: 16 }, { wch: 16 }, { wch: 18 }, { wch: 12 }, { wch: 16 }, { wch: 25 }
      ];
      ws['!freeze'] = { xSplit: 0, ySplit: 5 };
      ws['!autofilter'] = { ref: `A5:K${5 + sorted.length}` };

      const wb = XLSX.utils.book_new();
      XLSX.utils.book_append_sheet(wb, ws, 'Payment History');
      XLSX.writeFile(wb, `Payment_History_${new Date().toISOString().split('T')[0]}.xlsx`);

      showToast('Payment History.xlsx exported successfully!');
    } catch (err: any) {
      console.error(err);
      showToast('Failed to export Payment History report.', 'error');
    } finally {
      setLoadingReport(null);
    }
  };

  return (
    <div className="space-y-8 max-w-7xl mx-auto pb-16">
      {/* Toast Notification */}
      <AnimatePresence>
        {toast && (
          <motion.div
            initial={{ opacity: 0, y: -20, scale: 0.95 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: -20, scale: 0.95 }}
            className={cn(
              "fixed top-6 right-6 z-50 px-6 py-3.5 rounded-2xl shadow-2xl flex items-center gap-3 border backdrop-blur-xl",
              toast.type === 'success' 
                ? "bg-emerald-600 text-white border-emerald-400/30" 
                : "bg-red-600 text-white border-red-400/30"
            )}
          >
            {toast.type === 'success' ? <CheckCircle2 size={20} /> : <AlertCircle size={20} />}
            <span className="font-semibold text-sm">{toast.message}</span>
          </motion.div>
        )}
      </AnimatePresence>

      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold text-white tracking-tight">Enterprise Reporting & Excel Exports</h1>
          <p className="text-neutral-400 text-sm mt-1">Generate and download fully formatted, audit-ready Excel sheets (.xlsx) for pending collections, monthly summaries, and payment history.</p>
        </div>
        <div className="flex items-center gap-2 px-4 py-2 rounded-xl bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 text-xs font-bold uppercase tracking-wider">
          <Sparkles size={14} /> SheetJS Active
        </div>
      </div>

      {/* Three Report Cards Only */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
        
        {/* Card 1: Pending Payments */}
        <div className="bg-white/5 border border-white/10 rounded-3xl p-8 backdrop-blur-xl flex flex-col justify-between space-y-6 hover:border-emerald-500/30 transition-all group">
          <div>
            <div className="w-14 h-14 rounded-2xl bg-amber-500/10 border border-amber-500/20 flex items-center justify-center text-amber-400 mb-6 group-hover:scale-110 transition-transform">
              <Clock size={28} />
            </div>
            <h2 className="text-xl font-bold text-white mb-2">Pending Payments</h2>
            <p className="text-neutral-400 text-sm mb-6 leading-relaxed">
              Professional Excel export for all active pending collections, aging overdue days, reminder status, and AI risk scores.
            </p>
            <div className="space-y-2 py-4 border-t border-b border-white/10 text-xs text-neutral-300">
              <div className="flex justify-between"><span className="text-neutral-400">Last Generated:</span> <span className="font-mono">Today, 09:30 AM</span></div>
              <div className="flex justify-between"><span className="text-neutral-400">Records Count:</span> <span className="font-mono text-amber-400 font-bold">{pendingList.length > 0 ? pendingList.length : 3} Records</span></div>
              <div className="flex justify-between"><span className="text-neutral-400">Format:</span> <span className="font-mono text-emerald-400">Microsoft Excel (.xlsx)</span></div>
            </div>
          </div>
          
          <button
            onClick={handleExportPending}
            disabled={loadingReport === 'pending'}
            className="w-full py-3.5 bg-emerald-600 hover:bg-emerald-500 disabled:bg-emerald-600/50 text-white font-bold rounded-xl text-sm flex items-center justify-center gap-2 transition shadow-lg shadow-emerald-500/20 cursor-pointer"
          >
            {loadingReport === 'pending' ? (
              <>
                <Loader2 size={18} className="animate-spin" /> Generating Pending Payments...
              </>
            ) : (
              <>
                <Download size={18} /> Export Pending Payments (.xlsx)
              </>
            )}
          </button>
        </div>

        {/* Card 2: Monthly Report */}
        <div className="bg-white/5 border border-white/10 rounded-3xl p-8 backdrop-blur-xl flex flex-col justify-between space-y-6 hover:border-indigo-500/30 transition-all group">
          <div>
            <div className="w-14 h-14 rounded-2xl bg-indigo-500/10 border border-indigo-500/20 flex items-center justify-center text-indigo-400 mb-6 group-hover:scale-110 transition-transform">
              <BarChart3 size={28} />
            </div>
            <h2 className="text-xl font-bold text-white mb-2">Monthly Report</h2>
            <p className="text-neutral-400 text-sm mb-6 leading-relaxed">
              Comprehensive monthly financial summary including total revenue, collections, paid/pending invoice metrics, and collection rate.
            </p>
            <div className="space-y-2 py-4 border-t border-b border-white/10 text-xs text-neutral-300">
              <div className="flex justify-between"><span className="text-neutral-400">Last Generated:</span> <span className="font-mono">Yesterday, 11:45 PM</span></div>
              <div className="flex justify-between"><span className="text-neutral-400">Records Count:</span> <span className="font-mono text-indigo-400 font-bold">24 Invoices</span></div>
              <div className="flex justify-between"><span className="text-neutral-400">Format:</span> <span className="font-mono text-emerald-400">Microsoft Excel (.xlsx)</span></div>
            </div>
          </div>

          <button
            onClick={handleExportMonthly}
            disabled={loadingReport === 'monthly'}
            className="w-full py-3.5 bg-indigo-600 hover:bg-indigo-500 disabled:bg-indigo-600/50 text-white font-bold rounded-xl text-sm flex items-center justify-center gap-2 transition shadow-lg shadow-indigo-500/20 cursor-pointer"
          >
            {loadingReport === 'monthly' ? (
              <>
                <Loader2 size={18} className="animate-spin" /> Generating Monthly Report...
              </>
            ) : (
              <>
                <Download size={18} /> Export Monthly Report (.xlsx)
              </>
            )}
          </button>
        </div>

        {/* Card 3: Payment History */}
        <div className="bg-white/5 border border-white/10 rounded-3xl p-8 backdrop-blur-xl flex flex-col justify-between space-y-6 hover:border-purple-500/30 transition-all group">
          <div>
            <div className="w-14 h-14 rounded-2xl bg-purple-500/10 border border-purple-500/20 flex items-center justify-center text-purple-400 mb-6 group-hover:scale-110 transition-transform">
              <FileText size={28} />
            </div>
            <h2 className="text-xl font-bold text-white mb-2">Payment History</h2>
            <p className="text-neutral-400 text-sm mb-6 leading-relaxed">
              Complete payment history export sorted by newest first, containing transaction IDs, reference numbers, payment methods, and notes.
            </p>
            <div className="space-y-2 py-4 border-t border-b border-white/10 text-xs text-neutral-300">
              <div className="flex justify-between"><span className="text-neutral-400">Last Generated:</span> <span className="font-mono">Today, 02:15 PM</span></div>
              <div className="flex justify-between"><span className="text-neutral-400">Records Count:</span> <span className="font-mono text-purple-400 font-bold">{paymentHistoryList.length > 0 ? paymentHistoryList.length : 3} Transactions</span></div>
              <div className="flex justify-between"><span className="text-neutral-400">Format:</span> <span className="font-mono text-emerald-400">Microsoft Excel (.xlsx)</span></div>
            </div>
          </div>

          <button
            onClick={handleExportHistory}
            disabled={loadingReport === 'history'}
            className="w-full py-3.5 bg-purple-600 hover:bg-purple-500 disabled:bg-purple-600/50 text-white font-bold rounded-xl text-sm flex items-center justify-center gap-2 transition shadow-lg shadow-purple-500/20 cursor-pointer"
          >
            {loadingReport === 'history' ? (
              <>
                <Loader2 size={18} className="animate-spin" /> Generating Payment History...
              </>
            ) : (
              <>
                <Download size={18} /> Export Payment History (.xlsx)
              </>
            )}
          </button>
        </div>

      </div>
    </div>
  );
}
